server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

# host system
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log

# docker logs
- job_name: docker
  pipeline_stages:
    - docker: {}
  static_configs:
    - labels:
      job: docker
      __path__: /var/lib/docker/containers/*/*-json.log
  relabel_configs:
    - source_labels: [__meta_docker_container_name]
      target_label: container
    - source_labels: [__meta_docker_container_image]
      target_label: image


- job_name: journal
  journal:
    labels:
      job: journal
  relabel_configs:
    # services
    - source_labels:
        - __journal__systemd_unit
      target_label: unit
    # docker containers
    - source_labels:
        - __journal_container_name
      target_label: container  # use whatever label you like